spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tale?characterEncoding=utf8&serverTimezone=PST8PDT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hao
    password: 1122

  jpa:
    database: MySQL
    format_sql: true
    show-sql: true
    hibernate:
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      use-new-id-generator-mappings: false
