spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tale?characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: hao
    password: 1122

  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy